[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  conditions = {Path = "/_next/static/**"}

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[functions]
  included_files = ["prisma/**"]
  external_node_modules = ["@prisma/client"] 